---
title: Daan Kemps
description: I am trying to write a description to see if that works
baseurl: ''
remote_theme: YoussefRaafatNasry/portfolYOU
plugins:
  - jemoji
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md
author:
  name: Daan Kemps
  image: https://i.imgur.com/aeyyKaU.png
  email: contact@daankemps.com
  github: DoctorWaffles
  linkedin: daan-kemps-829205159
  steam: daankemps
  discord: 124970019493904380
  facebook: daan.kemps.5
  lastfm: daankemps
permalink: /blog/:title
collections:
  projects:
    output: true
    permalink: /projects/:name
  remote-projects:
    output: false
disqus:
  shortname: your-short-name-disqus
analytics:
  enabled: true
  google:
    tracking_id: G-GC1LTVDBKG
defaults:
  - scope:
      path: ''
      type: projects
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      comments: false
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - '*.log'